language: go

os:
  - linux

go_import_path: github.com/wamuir/svg-qr-code

go:
  - 1.15.x
  - tip

script:
     - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
     - bash <(curl -s https://codecov.io/bash)
